version: '3'
services:
  my-app:
    build:  # Building our application by refrencing the dockerfile/ or if you already had image just pass the name with its location
      context: .
      dockerfile: Dockerfile
    # image: ${docker-registry}/my-app:1.0
    ports:
     - 3000:3000
  mongodb:
    image: mongo
    ports:
     - 27017:27017
    environment:
     - MONGO_INITDB_ROOT_USERNAME=admin
     - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
     - mongo-data:/data/db   # for persisting data to volume
  mongo-express:
    image: mongo-express
    restart: always       # try to restart always if stopped due to any reason
    ports:
     - 8080:8081
    environment:
     - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
     - ME_CONFIG_MONGODB_ADMINPASSWORD=password
     - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
     - "mongodb"     # depends on help in concurrency, when mongodb start and run then mongo-express will connect to it.
volumes:   # Creating local volume so that db data may persist event container delete
  mongo-data:
    driver: local
